# Generated by Django 6.0.2 on 2026-05-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
