# Generated by Django 6.0.2 on 2026-05-25 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_map', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_es', models.CharField(max_length=100)),
                ('year_from', models.IntegerField(help_text='Start year of the period')),
                ('year_to', models.IntegerField(blank=True, help_text='End year — leave blank if ongoing', null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order in the filter sidebar')),
            ],
            options={
                'ordering': ['order', 'year_from'],
            },
        ),
        migrations.CreateModel(
            name='IncidentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='incidents/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first; 0 = cover image')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IncidentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display name, e.g. 'Clarín, 12 mar 1997'", max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name_en'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-date_occurred']},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='category',
            name='color_hex',
            field=models.CharField(default='#888888', help_text='Hex color used for map pins and UI pills, e.g. #1D9E75', max_length=7),
        ),
        migrations.AddField(
            model_name='incident',
            name='contributor_email',
            field=models.EmailField(blank=True, help_text='Private — used only for moderation follow-up', max_length=254),
        ),
        migrations.AddField(
            model_name='incident',
            name='contributor_name',
            field=models.CharField(blank=True, help_text='Public alias or name (shown on the detail sidebar)', max_length=120),
        ),
        migrations.AddField(
            model_name='incident',
            name='location_label',
            field=models.CharField(default=' ', help_text="Human-readable location, e.g. 'Pinamar, Buenos Aires'", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='rejection_note',
            field=models.TextField(blank=True, help_text='Optional note sent to the contributor if the submission is rejected'),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='memory_map.category'),
        ),
        migrations.AddField(
            model_name='incident',
            name='historical_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='memory_map.historicalperiod'),
        ),
        migrations.AddField(
            model_name='incidentimage',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='memory_map.incident'),
        ),
        migrations.AddField(
            model_name='incidentsource',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='memory_map.incident'),
        ),
    ]
